"""Write scripts to disk ahead of time, for code that ships without this package.

A library that ships Redis Lua answers to two audiences. Its maintainers want
what ``@script`` gives them: a body the linter reads, command names checked
against Redis, a signature mypy understands. Its users want one dependency
fewer and an import that costs nothing. Generating the Lua ahead of time serves
both: the scripts are written in Python, compiled when a maintainer runs this,
and shipped as plain strings that the library hands to redis-py's
``register_script`` exactly as it did before::

    python -m redis_lua_py generate myproj.scripts --out src/myproj/_lua.py

A test keeps the checked-in output honest::

    from redis_lua_py import codegen

    def test_generated_lua_is_current():
        codegen.check("myproj.scripts", "src/myproj/_lua.py")
"""

from __future__ import annotations

import difflib
import importlib
import re
from itertools import islice
from pathlib import Path
from types import ModuleType
from typing import Any

from ._compile import provenance
from ._script import CompiledScript
from .errors import RedisLuaError, StaleLuaError

__all__ = ["check", "collect", "generate", "render"]

#: Every compiled header carries this, which is how a directory of .lua files
#: tells the files written here from the ones somebody wrote by hand.
_MARKER = "-- Generated by redis-lua-py from "

#: A run of three quotes would close the triple-quoted literal early, and so
#: would a quote at the very end of it.
_QUOTE_RUNS = re.compile(r'"{3,}|"+\Z')

#: Characters Python's reader would change or refuse inside a literal. A bare
#: carriage return, for one, is read back as a newline.
_CONTROL = re.compile(r"[\x00-\x08\x0b-\x1f\x7f]")


def collect(module: ModuleType | str) -> dict[str, CompiledScript[Any]]:
    """Every script a module holds, by the name it is bound to, in definition order.

    A script bound to two names is collected once, under the first.
    """
    loaded = _load(module)
    scripts: dict[str, CompiledScript[Any]] = {}
    seen: set[int] = set()
    for name, value in vars(loaded).items():
        if isinstance(value, CompiledScript) and id(value) not in seen:
            seen.add(id(value))
            scripts[name] = value
    if not scripts:
        raise RedisLuaError(
            f"{loaded.__name__} holds no @script functions, so there is nothing to generate"
        )
    return scripts


def render(module: ModuleType | str, out: str | Path) -> dict[Path, str]:
    """The files :func:`generate` would write, and what each would hold.

    An ``out`` ending in ``.py`` is one Python module holding every script as a
    string constant, and importing nothing. Anything else is a directory, with
    one ``.lua`` file per script.
    """
    loaded = _load(module)
    scripts = collect(loaded)
    target = Path(out)
    if target.suffix == ".py":
        return {target: _python_module(loaded.__name__, scripts, target)}
    if target.suffix == ".lua":
        raise RedisLuaError(
            f"{out} names a single .lua file, but a module can hold several scripts. "
            "Pass a directory for one .lua file per script, or a .py path for one module."
        )
    return {target / f"{name}.lua": script.lua for name, script in scripts.items()}


def generate(module: ModuleType | str, out: str | Path) -> list[Path]:
    """Write a module's scripts under ``out``, and return the paths that changed.

    A file that already holds the right content is left alone. In a directory,
    a ``.lua`` file generated earlier for a script that no longer exists is
    removed; a ``.lua`` file without the generated header is never touched.
    """
    expected = render(module, out)
    changed: list[Path] = []
    for path, content in expected.items():
        if _read(path) != content:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            changed.append(path)
    for path in _leftovers(Path(out), expected):
        path.unlink()
        changed.append(path)
    return changed


def check(module: ModuleType | str, out: str | Path) -> None:
    """Raise :class:`StaleLuaError` unless ``out`` holds what :func:`generate` would write.

    The error carries a diff and the command that fixes it. It is also an
    ``AssertionError``, so a test that calls this fails rather than errors.
    """
    loaded = _load(module)
    expected = render(loaded, out)
    diffs = [
        _diff(path, _read(path), content)
        for path, content in expected.items()
        if _read(path) != content
    ]
    diffs += [_diff(path, _read(path), None) for path in _leftovers(Path(out), expected)]
    if diffs:
        raise StaleLuaError(
            f"{out} is out of date with {loaded.__name__}. Regenerate it with:\n\n"
            f"    python -m redis_lua_py generate {loaded.__name__} --out {out}\n\n"
            + "".join(diffs)
        )


def _load(module: ModuleType | str) -> ModuleType:
    return importlib.import_module(module) if isinstance(module, str) else module


def _read(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None


def _leftovers(directory: Path, expected: dict[Path, str]) -> list[Path]:
    """Generated .lua files in ``directory`` that no current script accounts for."""
    if directory.suffix == ".py" or not directory.is_dir():
        return []
    return sorted(
        path for path in directory.glob("*.lua") if path not in expected and _is_generated(path)
    )


def _is_generated(path: Path) -> bool:
    # The marker is on the second line of the header; the first is the name.
    with path.open(encoding="utf-8", errors="replace") as handle:
        return any(line.startswith(_MARKER) for line in islice(handle, 2))


def _diff(path: Path, before: str | None, after: str | None) -> str:
    lines = difflib.unified_diff(
        (before or "").splitlines(keepends=True),
        (after or "").splitlines(keepends=True),
        f"{path} ({'on disk' if before is not None else 'missing'})",
        f"{path} ({'generated' if after is not None else 'to be removed'})",
    )
    text = "".join(lines)
    return text if text.endswith("\n") else text + "\n"


def _python_module(module_name: str, scripts: dict[str, CompiledScript[Any]], out: Path) -> str:
    constants: dict[str, str] = {}
    for name in scripts:
        constant = name.upper()
        if constant in constants:
            raise RedisLuaError(
                f"{constants[constant]!r} and {name!r} would both be written as {constant}. "
                "Rename one of them."
            )
        constants[constant] = name

    # The path is repo-relative for the same reason the Lua header is: the file
    # is checked in, and must come out the same on every machine.
    parts = [
        f'"""Redis Lua scripts compiled by redis-lua-py from {module_name}. Do not edit.\n'
        "\n"
        "Regenerate with:\n"
        "\n"
        f"    python -m redis_lua_py generate {module_name} --out "
        f"{provenance(str(out.resolve()))}\n"
        '"""\n',
        "__all__ = [\n" + "".join(f'    "{constant}",\n' for constant in constants) + "]\n",
    ]
    for constant, name in constants.items():
        script = scripts[name]
        parts.append(
            f"# {name} -- {_call_order(script)}\n{constant} = {_python_string(script.lua)}\n"
        )
    return "\n".join(parts)


def _call_order(script: CompiledScript[Any]) -> str:
    """What a caller passing KEYS and ARGV by hand has to get right."""

    def spell(names: tuple[str, ...], variadic: str | None) -> str:
        return ", ".join(f"*{n}" if n == variadic else n for n in names) or "none"

    return (
        f"KEYS: {spell(script.keys, script.variadic_key)}; "
        f"ARGV: {spell(script.args, script.variadic_arg)}"
    )


def _python_string(text: str) -> str:
    """Render text as a triple-quoted Python literal that reads back exactly.

    Triple quotes keep the Lua readable in review, which is most of the point
    of checking it in; only what would break the literal is escaped.
    """
    body = text.replace("\\", "\\\\")
    body = _CONTROL.sub(lambda m: f"\\x{ord(m.group()):02x}", body)
    body = _QUOTE_RUNS.sub(lambda m: '\\"' * len(m.group()), body)
    return f'"""\\\n{body}"""'
