"""Regenerate ``src/redis_lua_py/_commands.py`` from the Redis source tree.

The compiler refuses a command Redis does not have, which means it needs to
know what Redis has. The authority for that is ``src/commands/*.json`` in the
Redis repository — the same files the server itself is built from — so this
downloads a tagged release and reads them rather than transcribing a list.

    uv run python scripts/generate_commands.py [version]

Run it when a Redis release adds commands, and commit the result. The command
table only gates the ``redis.<name>()`` spelling: ``redis.call('NEW.CMD', ...)``
is deliberately never checked, so a stale table can never block a caller.
"""

from __future__ import annotations

import io
import json
import sys
import tarfile
import urllib.request
from pathlib import Path

DEFAULT_VERSION = "8.10.1"
SOURCE = "https://github.com/redis/redis/archive/refs/tags/{version}.tar.gz"
TARGET = Path(__file__).resolve().parent.parent / "src" / "redis_lua_py" / "_commands.py"


def fetch(version: str) -> tuple[set[str], dict[str, set[str]]]:
    """Read every command definition out of a released Redis tarball.

    A subcommand's file names it bare -- ``hotkeys-get.json`` defines ``GET``
    with ``"container": "HOTKEYS"`` -- so entries are separated as they are
    read. Collecting them into one dict first would let ``HOTKEYS GET`` quietly
    displace plain ``GET``.
    """
    url = SOURCE.format(version=version)
    print(f"fetching {url}", file=sys.stderr)
    with urllib.request.urlopen(url) as response:
        payload = response.read()

    commands: set[str] = set()
    subcommands: dict[str, set[str]] = {}
    with tarfile.open(fileobj=io.BytesIO(payload), mode="r:gz") as archive:
        for member in archive.getmembers():
            parts = Path(member.name).parts
            if parts[1:3] != ("src", "commands") or not member.name.endswith(".json"):
                continue
            handle = archive.extractfile(member)
            if handle is None:  # pragma: no cover - directories were filtered out
                continue
            for name, spec in json.loads(handle.read()).items():
                container = spec.get("container")
                if isinstance(container, str):
                    subcommands.setdefault(container.upper(), set()).add(name.upper())
                else:
                    commands.add(name.upper())
    if not commands:
        raise SystemExit(f"no command definitions found in {url}")
    return commands, subcommands


def render(version: str, commands: set[str], subcommands: dict[str, set[str]]) -> str:
    lines = [
        '"""The commands Redis accepts, by name.',
        "",
        f"Generated by scripts/generate_commands.py from Redis {version}. Do not edit.",
        "",
        "``COMMANDS`` holds every command that is not a subcommand; ``SUBCOMMANDS``",
        "maps each container command to the subcommands it takes. Together they are",
        "what ``redis.<name>()`` is checked against, so that a name Redis does not",
        "have is refused at import rather than at the first execution of a branch.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        f'REDIS_VERSION = "{version}"',
        "",
        "COMMANDS: frozenset[str] = frozenset(",
        "    {",
    ]
    lines += [f'        "{name}",' for name in sorted(commands)]
    lines += ["    }", ")", "", "SUBCOMMANDS: dict[str, frozenset[str]] = {"]
    for container in sorted(subcommands):
        lines.append(f'    "{container}": frozenset(')
        lines.append("        {")
        lines += [f'            "{name}",' for name in sorted(subcommands[container])]
        lines += ["        }", "    ),"]
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> None:
    version = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_VERSION
    commands, subcommands = fetch(version)
    TARGET.write_text(render(version, commands, subcommands))
    print(
        f"wrote {TARGET.relative_to(Path.cwd())}: "
        f"{len(commands)} commands, {len(subcommands)} containers",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
