"""Turn a Python function into Lua.

The supported subset is deliberately small. Anything outside it raises
:class:`UnsupportedSyntax` pointing at the offending line, because a script
body that *looks* like Python but is never executed by Python is exactly the
place where a silent mistranslation would be most expensive.

The compiler itself is in layers, described in ``base``.
"""

from __future__ import annotations

import ast
import warnings
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any, TypeVar

from .. import _lua as lua
from .._script import CompiledScript
from ..errors import CompileError, NilTruncationWarning, render_location
from .analysis import unassigned_in_returns
from .helpers import helper_order, helper_source
from .source import parse_function, provenance
from .statements import Compiler

__all__ = [
    "SCRIPT_FLAGS",
    "CompiledBody",
    "check_flags",
    "compile_body",
    "compile_function",
    "helper_order",
    "helper_source",
    "provenance",
]

R = TypeVar("R")


#: The flags Redis 7 defines, for a script's `#!lua` line and for a function.
SCRIPT_FLAGS = frozenset(
    {"no-writes", "allow-oom", "allow-stale", "no-cluster", "allow-cross-slot-keys"}
)


def check_flags(flags: tuple[str, ...], *, owner: str) -> tuple[str, ...]:
    """Refuse a flag Redis does not define, where the mistake is made."""
    for flag in flags:
        if flag not in SCRIPT_FLAGS:
            raise CompileError(
                f"{owner}: unknown flag {flag!r}; Redis defines {', '.join(sorted(SCRIPT_FLAGS))}"
            )
    return flags


@dataclass(frozen=True)
class CompiledBody:
    """A function compiled to Lua, before it is framed as a script or a library function."""

    name: str
    #: The prelude binding KEYS and ARGV, and the statements; no helpers.
    body: str
    #: The helpers the body calls, in the order they must be emitted.
    helpers: tuple[str, ...]
    params: tuple[str, ...]
    keys: tuple[str, ...]
    args: tuple[str, ...]
    variadic_key: str | None
    variadic_arg: str | None
    doc: str | None
    filename: str
    first_lineno: int
    #: Each parameter's annotation as written, in the order of ``params``.
    param_annotations: tuple[str | None, ...] = ()
    return_annotation: str | None = None
    keyword_only: tuple[str, ...] = ()

    @property
    def provenance(self) -> str:
        return f"{provenance(self.filename)}:{self.first_lineno}"


def compile_function(
    func: Callable[..., R],
    *,
    name: str | None = None,
    header: bool = True,
    flags: tuple[str, ...] = (),
) -> CompiledScript[R]:
    compiled = compile_body(func, name=name)
    parts: list[str] = []
    if flags:
        # Redis only reads a script's flags from a shebang on its first line.
        parts.append(f"#!lua flags={','.join(flags)}")
    if header:
        parts.append(
            f"-- {compiled.name}\n"
            f"-- Generated by redis-lua-py from {compiled.provenance}. Do not edit."
        )
    parts.extend(helper_source(helper) for helper in compiled.helpers)
    parts.append(compiled.body)

    return CompiledScript(
        name=compiled.name,
        lua="\n".join(parts) + "\n",
        params=compiled.params,
        keys=compiled.keys,
        args=compiled.args,
        variadic_key=compiled.variadic_key,
        variadic_arg=compiled.variadic_arg,
        doc=compiled.doc,
        source=f"{compiled.filename}:{compiled.first_lineno}",
        param_annotations=compiled.param_annotations,
        return_annotation=compiled.return_annotation,
        keyword_only=compiled.keyword_only,
    )


def compile_body(func: Callable[..., Any], *, name: str | None = None) -> CompiledBody:
    node, filename, first_lineno, lines = parse_function(func)
    compiler = Compiler(
        node,
        filename=filename,
        first_lineno=first_lineno,
        lines=lines,
        # Receivers are resolved against the defining module, so the namespace
        # is recognised under whatever name it was imported as.
        globalns=getattr(func, "__globals__", {}),
    )

    prelude = compiler.compile_signature()
    compiler.collect_assigned()

    body = node.body
    doc = ast.get_docstring(node)
    if doc is not None:
        body = body[1:]

    statements = compiler.block(body)
    if compiler.hoisted:
        prelude.append(lua.Local(sorted(set(compiler.hoisted)), []))

    for element, unassigned in unassigned_in_returns(body, set(compiler.params), compiler.known):
        warnings.warn_explicit(
            render_location(
                f"{unassigned!r} is not assigned on every path to this return, and a nil "
                "in a returned table truncates the reply there",
                filename=filename,
                lineno=first_lineno + element.lineno - 1,
                col=element.col_offset,
                source_line=lines[element.lineno - 1] if element.lineno <= len(lines) else None,
                hint="Give it a value before the branch, so that every branch returns a "
                "table of the same shape.",
            ),
            NilTruncationWarning,
            filename,
            first_lineno + element.lineno - 1,
        )

    return CompiledBody(
        name=name or func.__name__,
        body=lua.emit(prelude + statements).rstrip(),
        helpers=tuple(helper_order(compiler.helpers)),
        params=tuple(compiler.params),
        keys=tuple(compiler.keys),
        args=tuple(compiler.args),
        variadic_key=compiler.variadic_key,
        variadic_arg=compiler.variadic_arg,
        doc=doc,
        filename=filename,
        first_lineno=first_lineno,
        # Kept as source text: the compiler does not need them, but a generated
        # function repeats them in its signature.
        param_annotations=tuple(
            None if arg.annotation is None else ast.unparse(arg.annotation)
            for arg in [*node.args.args, *node.args.kwonlyargs]
        ),
        return_annotation=None if node.returns is None else ast.unparse(node.returns),
        keyword_only=tuple(arg.arg for arg in node.args.kwonlyargs),
    )
